### PR TITLE
Update docs for v1.0.0 beta

### PR DESCRIPTION
**Pull request by mrdavidlaing**
This updates the Log Search documentation for the v1.0.0 beta tile.

It needs to be merged along with:
* https://github.com/pivotal-cf/docs-book-pivotalcf/tree/logsearch branch and the 
* https://github.com/pivotal-cf/docs-layout-repo/tree/logsearch branch

Thanks!

### CODE REVIEW

**Comment by mrdavidlaing** [comment]
@kimahoff - Could you merge these when you get a change.  Its not perfect yet; but its a good starting point for refinement.

Thanks!

**Comment by ljarzynski** [comment]
Hi @mrdavidlaing, thanks for the PR! Looks very thorough. We'll need to do a couple thing before merging. For instance, we recently moved the services docs "out of docs-book-pivotalcf and into docs-pcf-services. Also, we'll make sure all the file extensions are ".html.md.erb" and put the images into their own folder, etc. We'll create another story for the actual review of the content after merging. As you said, this is a great starting point! 

Also, is the beta tile currently available on PivNet?

**Comment by ljarzynski** [comment]
@mrdavidlaing: We made the changes described above. Also, we commented out the "maintaining" and "upgrading" pages in the subnav file, as they do not have content yet. We created a story for reviewing the content of the docs, and you can follow the progress here: https://www.pivotaltracker.com/story/show/120402515. We may reach out with questions.

**Comment by mrdavidlaing** [comment]
@ljarzynski Thanks!

**Pull request merged**
