### PR TITLE
Document how to send log search data to splunk

### PR DESCRIPTION
**Pull request by MasslessParticle**

### CODE REVIEW

**Comment by mrdavidlaing** [comment]
@kimahoff - Could you merge this extra documentation & publish to docs.pivotal.io/logsearch for us please. 

 Its relevant to the existing v1.0.0 tile.

Thanks!

**Comment by ljarzynski** [comment]
@mrdavidlaing @kimahoff Currently looking at this. Will build locally first to make sure everything looks good.

**Comment by MasslessParticle** [comment]
@ljarzynski Thanks!

FWIW; I think the screenshot images might be a bit big.

**Comment by ljarzynski** [comment]
@MasslessParticle Ok, thanks. I can resize them.

**Pull request merged**
