### PR TITLE
WIP Updates for v1.0.2 release

### PR DESCRIPTION
**Pull request by mrdavidlaing**
Contains updated documentation for the v1.0.2 release.

### CODE REVIEW

**Comment by ljarzynski** [comment]
@mrdavidlaing blocking the story for now. Let us know when it's ready to go! Oct?

**Comment by AmberAlston** [comment]
@mrdavidlaing Besides needing to update this PR to reflect that this release will actually be **1.0.2** instead of 1.0.1, is all the rest of this content correctly updated for the changes in the intended 1.0.2 release? We have 1.0.2 working through the pipeline and near complete. We'd want to update these docs with that 1.0.2 release, so I want to ensure they are ready to go from your perspective. (FYI @ljarzynski )

**Comment by AmberAlston** [comment]
@mrdavidlaing Being asked this morning if this patch will fix some outstanding issues (ex "multiple ingestor fix"), made me realize we need to get the RN and KI updated for this bump as well. Since we didn't develop the bump and don't easily know all the stories that went in to it, we'd need your help drafting updates for the RN/KI in order to release 1.0.2 with properly updated docs. (fyi @ljarzynski )

**Comment by mrdavidlaing** [comment]
@AmberAlston, @ljarzynski - This is ready for review; correction & merging.

Please feel free to make any changes & merge without my input.

**Comment by AmberAlston** [comment]
@mrdavidlaing Thanks! I think we have good coverage now on the needed docs changes. When we have the final tile ready to release, I'll work with @ljarzynski as needed to coordinate pushing these out with the 1.0.2 tile release

**Comment by ljarzynski** [comment]
@AmberAlston The story for this was buried in our icebox, but I just moved it up so one of us on docs can review before it goes live.

**Comment by AmberAlston** [comment]
Thank you @ljarzynski David is doing some final acceptance by mid-week and then I'm expecting to want to release this mid to late this week. I'll keep the docs team updated as we get closer to knowing we are a go for release

**Pull request merged**
